/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package exploradorpersonas;

import java.util.ArrayList;

/**
 *
 * @author Juan C. Jiménez
 */
public class exploraPersonas extends javax.swing.JFrame {
    
    private ArrayList<persona> gente;
    private boolean insertar;

    /**
     * Creates new form exploraPersonas
     */
    public exploraPersonas() {
        initComponents();
        cargaGente();
        mostrarRegistro(0);
    }

    private void cargaGente(){
        this.gente = new ArrayList<persona>();
        String [] aficiones = {"Ir al cine","Tomar cerveza"};
        this.gente.add(new persona("11111111A","Lola","Flores","Calle Agua s/n",true,aficiones,true));
        String [] aficiones2 = {"Pasear","Tomar cerveza"};
        this.gente.add(new persona("22222222B","Pepe","Palotes","Calle gran via, 1",false,aficiones2,true));
        String [] aficiones3 = {"Ir al Cine","Pasear"};
        this.gente.add(new persona("33333333C","Luis","Pérez","Calle laga, 100",false,aficiones3,false));
        String [] aficiones4 = {"Programar","Quedar con amigos"};
        this.gente.add(new persona("44444444D","Ana","López","Calle sin salida, 2",true,aficiones4,false));
    }
    
    private void mostrarRegistro(int i){
        //Preparamos los labels
        lX.setText(Integer.toString(i+1));
        lY.setText(Integer.toString(this.gente.size()));
        tDNI.setText(this.gente.get(i).getDNI());
        tNombre.setText(this.gente.get(i).getNombre());
        tApellidos.setText(this.gente.get(i).getApellidos());
        tDireccion.setText(this.gente.get(i).getDireccion());
        //Sexo
        brFemenino.setSelected(this.gente.get(i).isSexo());   //Femenino
        brMasculino.setSelected(!this.gente.get(i).isSexo()); //Masculino
        //Aficiones
        cbCerveza.setSelected(false);
        cbCine.setSelected(false);
        cbPasear.setSelected(false);
        cbProgramar.setSelected(false);
        cbTeatro.setSelected(false);
        cbAmigos.setSelected(false);
        for(String aficion : this.gente.get(i).getAficiones()){
            if(aficion.toLowerCase().equals("tomar cerveza"))
                cbCerveza.setSelected(true);
            else if(aficion.toLowerCase().equals("ir al cine"))
                cbCine.setSelected(true);
            else if(aficion.toLowerCase().equals("pasear"))
                cbPasear.setSelected(true);
            else if(aficion.toLowerCase().equals("ir al teatro"))
                cbTeatro.setSelected(true);
            else if(aficion.toLowerCase().equals("programar"))
                cbProgramar.setSelected(true);
            else if(aficion.toLowerCase().equals("quedar con amigos"))
                cbAmigos.setSelected(true);
        }
        //Mayor de Edad
        cbEdad.setSelectedIndex(this.gente.get(i).isMayorEdad()?1:2);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gSexo = new javax.swing.ButtonGroup();
        label1 = new javax.swing.JLabel();
        tDNI = new javax.swing.JTextField();
        label2 = new javax.swing.JLabel();
        tNombre = new javax.swing.JTextField();
        bPrimero = new javax.swing.JButton();
        bAnterior = new javax.swing.JButton();
        bSiguiente = new javax.swing.JButton();
        bUltimo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lX = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lY = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        tApellidos = new javax.swing.JTextField();
        label4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tDireccion = new javax.swing.JTextArea();
        label5 = new javax.swing.JLabel();
        cbCerveza = new javax.swing.JCheckBox();
        cbCine = new javax.swing.JCheckBox();
        cbPasear = new javax.swing.JCheckBox();
        cbTeatro = new javax.swing.JCheckBox();
        cbProgramar = new javax.swing.JCheckBox();
        cbAmigos = new javax.swing.JCheckBox();
        label6 = new javax.swing.JLabel();
        cbEdad = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        label7 = new javax.swing.JLabel();
        brFemenino = new javax.swing.JRadioButton();
        brMasculino = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CRUD DE Personas");

        label1.setText("DNI");

        label2.setText("Nombre");

        bPrimero.setText("|<");
        bPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPrimeroActionPerformed(evt);
            }
        });

        bAnterior.setText("<<");
        bAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnteriorActionPerformed(evt);
            }
        });

        bSiguiente.setText(">>");
        bSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSiguienteActionPerformed(evt);
            }
        });

        bUltimo.setText(">|");
        bUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUltimoActionPerformed(evt);
            }
        });

        jLabel1.setText("Registro");

        lX.setText("X");

        jLabel3.setText("de");

        lY.setText("Y");

        label3.setText("Apellidos");

        label4.setText("Dirección");

        tDireccion.setColumns(20);
        tDireccion.setRows(5);
        jScrollPane1.setViewportView(tDireccion);

        label5.setText("Aficiones");

        cbCerveza.setText("Tomar cerveza");

        cbCine.setText("Ir al cine");

        cbPasear.setText("Pasear");

        cbTeatro.setText("Ir al teatro");

        cbProgramar.setText("Programar");

        cbAmigos.setText("Quedar con amigos");

        label6.setText("¿Es mayor de edad?");

        cbEdad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "SI", "NO" }));

        jButton1.setText("Nueva Persona");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        label7.setText("Sexo:");

        gSexo.add(brFemenino);
        brFemenino.setText("Femenino");

        gSexo.add(brMasculino);
        brMasculino.setText("Masculino");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lX)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lY))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label1)
                                    .addComponent(label2)
                                    .addComponent(label3)
                                    .addComponent(label4))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tDNI)
                                    .addComponent(tNombre)
                                    .addComponent(tApellidos)
                                    .addComponent(jScrollPane1)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(66, 66, 66)
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(bPrimero, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8)
                                        .addComponent(bSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(label5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbCerveza)
                                            .addComponent(cbTeatro)
                                            .addComponent(label6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbCine)
                                            .addComponent(cbProgramar)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addComponent(cbEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbPasear)
                                            .addComponent(cbAmigos)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(label7)
                                        .addGap(42, 42, 42)
                                        .addComponent(brFemenino)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(brMasculino)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lX)
                    .addComponent(jLabel3)
                    .addComponent(lY))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label1)
                    .addComponent(tDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label2)
                    .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label3)
                    .addComponent(tApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(brFemenino, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(brMasculino)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCerveza)
                    .addComponent(cbCine)
                    .addComponent(cbPasear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTeatro)
                    .addComponent(cbProgramar)
                    .addComponent(cbAmigos))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label6)
                    .addComponent(cbEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bPrimero, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUltimoActionPerformed
        // TODO add your handling code here:
        mostrarRegistro(this.gente.size()-1);
        this.insertar = false;
    }//GEN-LAST:event_bUltimoActionPerformed

    private void bPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPrimeroActionPerformed
        // TODO add your handling code here:
        mostrarRegistro(0);
        this.insertar = false;
    }//GEN-LAST:event_bPrimeroActionPerformed

    private void bAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnteriorActionPerformed
        // TODO add your handling code here:
        if(Integer.parseInt(lX.getText())==1)
            mostrarRegistro(this.gente.size()-1);
        else
            mostrarRegistro(Integer.parseInt(lX.getText())-2);
        this.insertar = false;
    }//GEN-LAST:event_bAnteriorActionPerformed

    private void bSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSiguienteActionPerformed
        // TODO add your handling code here:
        if(Integer.parseInt(lX.getText())==this.gente.size())
            mostrarRegistro(0);
        else
            mostrarRegistro(Integer.parseInt(lX.getText()));
        this.insertar = false;
    }//GEN-LAST:event_bSiguienteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        tDNI.setText("");
        tNombre.setText("");
        tApellidos.setText("");
        tDireccion.setText("");
        brFemenino.setSelected(false);
        brMasculino.setSelected(false);
        cbCerveza.setSelected(false);
        cbCine.setSelected(false);
        cbPasear.setSelected(false);
        cbProgramar.setSelected(false);
        cbTeatro.setSelected(false);
        cbAmigos.setSelected(false);
        cbEdad.setSelectedIndex(0);
        this.insertar = true;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(this.insertar){ //Insertamos
            String [] aficiones = new String[6];
            int i=0;
            if(cbAmigos.isSelected()){
                aficiones[i] = "Quedar con amigos";
                i++;
            }
            if(cbCerveza.isSelected()){
                aficiones[i] = "Tomar cerveza";
                i++;
            }
            if(cbCine.isSelected()){
                aficiones[i] = "Ir al cine";
                i++;
            }
            if(cbPasear.isSelected()){
                aficiones[i] = "Pasear";
                i++;
            }
            if(cbTeatro.isSelected()){
                aficiones[i] = "Ir al Teatro";
                i++;
            }
            if(cbProgramar.isSelected()){
                aficiones[i] = "Programar";
                i++;
            }
            
            this.gente.add(new persona(tDNI.getText(),
                                       tNombre.getText(),
                                       tApellidos.getText(),
                                       tDireccion.getText(),
                                       brFemenino.isSelected(),
                                       aficiones,
                                       cbEdad.getSelectedIndex()==1?true:false));
            this.insertar = false;
            mostrarRegistro(this.gente.size()-1);
        }else{ //Actualizamos
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(exploraPersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(exploraPersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(exploraPersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(exploraPersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new exploraPersonas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAnterior;
    private javax.swing.JButton bPrimero;
    private javax.swing.JButton bSiguiente;
    private javax.swing.JButton bUltimo;
    private javax.swing.JRadioButton brFemenino;
    private javax.swing.JRadioButton brMasculino;
    private javax.swing.JCheckBox cbAmigos;
    private javax.swing.JCheckBox cbCerveza;
    private javax.swing.JCheckBox cbCine;
    private javax.swing.JComboBox<String> cbEdad;
    private javax.swing.JCheckBox cbPasear;
    private javax.swing.JCheckBox cbProgramar;
    private javax.swing.JCheckBox cbTeatro;
    private javax.swing.ButtonGroup gSexo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lX;
    private javax.swing.JLabel lY;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JTextField tApellidos;
    private javax.swing.JTextField tDNI;
    private javax.swing.JTextArea tDireccion;
    private javax.swing.JTextField tNombre;
    // End of variables declaration//GEN-END:variables
}
